# This is a basic workflow to help you get started with Actions

name: Milestone Closure

# Controls when the workflow will run
on:
  milestone:
    types: [closed]
  workflow_dispatch:
    inputs:
      milestoneId:
        description: 'Milestone ID'     
        required: true
        default: '1'

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: releases
        USE_MILESTONE_TITLE: "true"
    - name: Upload Release Notes to Wiki
      uses: docker://decathlon/wiki-page-creator-action:latest
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        ACTION_MAIL: ${{ vars.ACTION_MAIL }}
        ACTION_NAME: ${{ vars.ACTION_NAME }}
        REPO_NAME: ${{ vars.REPO_NAME }}
